# Generated by Django 4.2.6 on 2023-10-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lungHealth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='hospital',
            field=models.CharField(max_length=100),
        ),
    ]
