# Generated by Django 4.2.6 on 2023-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lungHealth_app', '0002_alter_medico_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hospital',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='paciente',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
    ]
